services:
  lftp-sync:
    build: .
    volumes:
      - ./data:/sync-folder
    container_name: lftp-sync
    environment:
      FTP_USER: "user"
      FTP_PASS: "pass"
      FTP_HOST: "host"
      REMOTE_FOLDER: "/static"
    restart: always
